### ISSUE TITLE
Inspection to validate Camel endpoints

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#10]
We could add a code inspection that discovers all your Camel endpoints and then uses the validate API from CamelCatalog to validate if they are okay or not, and then report issues.

**Comment by fharms** [comment]
I have been looking into the code inspection API and it's not obvious to use in this case IMHO. The inspection API is more for static code analysis and I this is more a validation of the endpoint.

Wouldn't this be more suitable to show in message view (Information, Warning, Compiler errors)?

**Comment by fharms** [comment]
It might be a better we hook into the Builder API http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/external_builder_api.html

**Comment by fharms** [comment]
Found this for localInspection, but unfortunately haven't found any documentation yet.

Still searching....

```XML
<localInspection language="XML" shortName="AntDuplicateTargetsInspection" bundle="messages.AntBundle" key="ant.duplicate.targets.inspection"
                     groupKey="ant.inspections.display.name" enabledByDefault="true" level="ERROR"
                     implementationClass="com.intellij.lang.ant.validation.AntDuplicateTargetsInspection"/>
```

**Comment by fharms** [comment]
What do you mean by different level? 

I would expect a warning in the messages view when you build the project. Do you think of something else?

**Comment by fharms** [comment]
I think I will try to use the plugins/maven/jps-plugin as reference plug-in for the validation

**Comment by davsclaus** [comment]
Its likely two of the same thing

- warnings in message view when building, like you get deprecated warnings from the compiler
- something else to flag / indicate directly in the source code editor a problem

**Comment by adrianbumbas** [comment]
Would an [Annotator](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/annotator.html) do the trick?

**Comment by fharms** [comment]
That might not be a bad idea to use the Annotator instead. 

I'll will look into it.

**Comment by fharms** [comment]
Early version of end point validation
<img width="611" alt="screen shot 2017-01-07 at 08 48 47" src="https://cloud.githubusercontent.com/assets/1123285/21740298/48d596a0-d4b6-11e6-9736-f099a5f42cd4.png">

**Comment by fharms** [comment]
The annotator seems to be a good way of validate the end point. My only concern is performance since this happen all the time.

I do restrict it when it should validate, so it all comes down to if we can be intelligent when to validate and the performance of the CamelCatalog validation.

**Comment by davsclaus** [comment]
Nice work. I wonder if the annotator only triggers for the current file you have open?
And how often does it run, does IDEA have like a 2-5 second run interval or something?

The catalog validation would be fast enough, its only doing cpu computations - and all data is in-memory only from the camel catalog.

What we could do is to add a hit/miss cache so if the uris are not changed we can return previous response. Then we can skip the parsing, which can speedup the thing.

Also we should have an option in the preference where people can turn this validation on | off.

Also maybe if the uri is long, we should only show the tooltip with the invalid option, eg

    bridgeErrorHandler=fiSH invalid boolean value: fiSH

Or maybe even shorter

    invalid boolean value: fiSH

Also mind the validator can return 2 or more errors, so how does that look like?

**Comment by fharms** [comment]
The Annotator only run for the file you have open/active in the editor, so I guess it limit to active editors. I don't know what the run interval is, but it seems to be binded to when you stop typing.

The hit/miss cache is a good idea for make it faster. We just need to be intelligent about when the case should invalidate. No need to cache uris for Editor not open anymore.

Unfortunately you can only have one annotation for each PsiElement as far i know, and since the PsiElement is not broken up on text expression we can only validate on at the time.

@davsclaus is there way to only get the invalidation string or do I have to parse the String?

**Comment by davsclaus** [comment]
The `EndpointValidationResult` has detailed validation errors. You can find each problem in those maps where the key is the option name.

Take a look at the source code at
https://github.com/apache/camel/blob/master/platforms/catalog/src/main/java/org/apache/camel/catalog/EndpointValidationResult.java

And see for example how that summary does it

**Comment by davsclaus** [comment]
Yeah for cache we can maybe have some idea listener that tells us about if current editor is changed (if an editor change means to switch to another source file) then we can trigger the cache to clear

**Comment by fharms** [comment]
I got the code implemented and most of the unit test in place. 

But I'm still struggling with finding a way to setup the unit test with SDK language level to solve an issue with it can't resolve String when running highlight test

**Comment by fharms** [comment]
Next step is to get validation of simple expression to work properly
