### ISSUE TITLE
Restructure source into multi maven module

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#102]
We should have a root pom and then maven sub modules for different things.

As we would need a module for a custom camel component which we need for some testing.
Then a module for the idea plugin

And in the future a api module with a reusable api and code for other ide's to reuse etc.

**Comment by davsclaus** [comment]
Will get started on this now but if its too invasive we may do it on a 0.3.x branch and let master be for 0.2.x in case we want to do a 0.2.3 release.

However ideally if this pan out well we should move ahead as it paves the way for supporting custom Camel components.

**Comment by fharms** [comment]
I'm fine with we are doing it now. It's not gonna have a big impact on my task since it mostly new files for the issue I'm working on

**Comment by davsclaus** [comment]
@fharms the code has been merged.

You may need to update your IDE settings a bit, or re-create the Run .. Plugin which I had to do.

**Comment by fharms** [comment]
@davsclaus thanks, I also had to update the location of the plug-in xml file in the module settings under the plug-in tab
