### ISSUE TITLE
Camel gutter icon - Make it not clickable

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#108]
Currently it shows a choice among various elements from the line.

We should make it non clickable until we find a good action to do, such as a find usage or something to jump to other routes that is calling this etc or something.

**Comment by davsclaus** [comment]
The setTarget must be called, so we cant seem to not make it clickable. However we should try to find the literal element for the endpoint, so there is only 1 target instead of this weird drop down you get today with 6 elements.

**Comment by incorrectusername** [comment]
hello , can i solve this? can you please tell me how to proceed?

**Comment by davsclaus** [comment]
You can try to make this method return the PsiElement instead of boolean
https://github.com/davsclaus/camel-idea-plugin/blob/master/camel-idea-plugin/src/main/java/org/apache/camel/idea/util/IdeaUtils.java#L147

Then you return the element which contains the literal of the endpoint, or attribute for xml. Then you can use that as the target, so hopefully the click will only show 1 in the list, which selects the endpoint uri in the editor.

I tired to set it to null or remove it completely but then IDEA gave me an error.

I am not sure if we can set some other dummy target or something to "remove the click".

Or try to see what some of the other plugins have done for gutter icons.
https://github.com/JetBrains/intellij-community/tree/master/plugins

**Comment by davsclaus** [comment]
Maybe we can provide an empty element object or something instead of the psi element so it may cause the click to not do anything.

**Comment by adrianbumbas** [comment]
Indeed by setting `.setTargets(Collections.emptyList())` the icon will become not clickable.

But instead of making it not clickable maybe we can use it to navigate to related routes using from-to. I'm working on something that looks like this
![image](https://cloud.githubusercontent.com/assets/1636509/22072598/22455502-dda3-11e6-8e31-caa08e782563.png)

 By clicking on the gutter icon on the line ` <from uri="direct:deliveries"/>` (that is hidden by the popup) i can navigate to the `  <to uri="direct:deliveries"/>` occurrences on lines 49 and 55 (highlight is mine)

I don't know how useful is this and what can be the limitations.@davsclaus and @fharms  what do you think?

**Comment by davsclaus** [comment]
@adrianbumbas that is very cool.

Related to this.

We have a ticket about find-usages. We should have some support for linking routes together in the future, possible with an api in camel-catalog that can be a bit smarter about this.

So ideally one day we find out how routes are linked together and have icons in the gutter to navigate between them.

**Comment by adrianbumbas** [comment]
@davsclaus Are you talking about #23 ? I'm not sure that this is the same thing.

**Comment by davsclaus** [comment]
Its related because its about find out where other Camel routes are calling this route (find usages).

**Comment by adrianbumbas** [comment]
ok, i see. Then what is the plan for this? What can i do?

**Comment by davsclaus** [comment]
Maybe first PR is to add that empty, so nothing happens.

Then work on what you currently are doing with that list.

**Comment by davsclaus** [comment]
@adrianbumbas I suggest to create a new ticket about click on camel icon in gutter to make it navigateable to routes. Then we can close this ticket which is about not clickable

**Comment by adrianbumbas** [comment]
I will do that.
