### ISSUE TITLE
Log to idea.log 

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#119]
We should do a bit of logging to idea.log which is the log file.

I wonder if there is some plugin sdk api we can use to log for that.

And for some special cases we could log in the event log as well which can notify the user about a potential issue.

**Comment by fharms** [comment]
The right way is to use the IDEA logger class (com.intellij.openapi.diagnostic.Logger)

**Comment by davsclaus** [comment]
Thanks, I found some code as well to use notification so we can write to the event log so the user can see it as well
