### ISSUE TITLE
Preference - Add or remove property placeholder keys to ignore

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#135]
In preference

- Add or remove to the property placeholder ignore list

Currently we have a number of hardcoded. We should make this configurable from the preference.

**Comment by fharms** [comment]
I take this because this is an issue on my project :-)

**Comment by davsclaus** [comment]
Good luck. I suggest to look at some of the existing plugins how they do add/remove style preferences.

Worst case its some text area where you can edit the lines and use comma or new line to separate them

**Comment by fharms** [comment]
I found an example here on how to setup panel, list and buttons. But it will require a bit more work than first anticipated  https://github.com/jshiell/checkstyle-idea

**Comment by fharms** [comment]
Working progress :-)
<img width="756" alt="screen shot 2017-01-18 at 21 31 16" src="https://cloud.githubusercontent.com/assets/1123285/22081962/0d7b7da4-ddc6-11e6-897d-f0d3c4b30865.png">

**Comment by davsclaus** [comment]
Whoa that looks nice, you are java swing master soon ;)

**Comment by fharms** [comment]
@davsclaus A Intellij developer dude suggested on twitter we should move Camel Preference to under Languages & Frameworks

**Comment by davsclaus** [comment]
Okay if you think that is a good idea then you are welcome to move it, remember to update the readme file which point to other settings

**Comment by davsclaus** [comment]
@fharms great work, do you mind updating the changelog in plugin.xml

And you are also welcome to do a 0.3.5 release.

**Comment by fharms** [comment]
@davsclaus I completely forgot about the change log.

I'll make a release later today
