### ISSUE TITLE
Real time endpoint validator - In all endpoints

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#141]
Currently its only for consumer or producer endpoints.

We should let it work in same places as smart completions do

For example here in the dead letter channel the uri is not real time validated

![screen shot 2017-01-09 at 2 06 21 pm](https://cloud.githubusercontent.com/assets/477100/21767499/dae18774-d674-11e6-98d8-30bf4445b7a0.png)

**Comment by davsclaus** [comment]
You can also have annotations as `@Consume` etc where we can / should do validation

**Comment by fharms** [comment]
So this basic mean we should validate if the URI contains a known camel component instead of also checking for if it a producer and consumer endpoints?

**Comment by davsclaus** [comment]
Yes so its the same as smart completion.

For the latter there is a ticket about consumer and producer only mode where we can tell the validator about this to do even stricter validation
https://github.com/davsclaus/camel-idea-plugin/issues/129

This required a new change in camel-catalog which I implemented today.

**Comment by fharms** [comment]
I will fix this later today. It should be pretty easy to implement

**Comment by davsclaus** [comment]
I think you fixed this now
