### ISSUE TITLE
Real time simple validator

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#143]
Like for endpoint uris, we can do for simple languge.

Its a bit tricky with the classloader, but I think I got a solution which requires a change in camel-catalog which I will fix today.

However we would also need to discover if the simple language is used as a predicate or expression. And that is a bit harder to do. We do it in the maven plugin, so let me try to dig up some code there.

**Comment by davsclaus** [comment]
![screen shot 2017-01-09 at 8 54 14 pm](https://cloud.githubusercontent.com/assets/477100/21780969/cf8c4cf4-d6ad-11e6-8e07-6567a7438aa7.png)

We should likely try to make Camel report it easier for you to know at which position the error is, but the error message in text says its ay the 6th character.

**Comment by davsclaus** [comment]
Okay this requires Apache Camel to publish an updated SNAPSHOT to their snapshot repo so the CI server can pickup the changes, so I have to wait a bit with this fix.

**Comment by fharms** [comment]
Yeah that was one of the problems I was struggling with before I left it and the current implementation of simple validation is not tested because of the class loader.

**Comment by davsclaus** [comment]
Okay got the simple validation to return the index of the problem (if its possible)
https://issues.apache.org/jira/browse/CAMEL-10684

Then the result class has a `getIndex` method which you can use to know where in the string the problem is starting at. Which you can use to mark the red line at that starting point.

**Comment by fharms** [comment]
@devsclaus I will look into this later today and maybe we can make a release tomorrow

**Comment by davsclaus** [comment]
I will do a 0.3.1 with the current fixes, then we can do the simple later as it needs a little bit more love

**Comment by davsclaus** [comment]
I have pushed the code for making the simple validator work with the classloading.

The result of the validation now includes a `getIndex` method you can use to position the red underline where the problem is. If the index is 0 then its because of a more general problem.

And it needs to be added for all the other languages, its for java only now in the plugin xml file.

**Comment by davsclaus** [comment]
@fharms okay so what is left here to do is to improve the response message we show the end user

At
https://github.com/davsclaus/camel-idea-plugin/blob/master/camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelSimpleAnnotator.java#L57

There is a new `getIndex` method on the result you can use to know the offset in the simple text where the problem is.

**Comment by davsclaus** [comment]
And then you need to add the simple validation to all the other languages as well.

**Comment by fharms** [comment]
Is it correctly understood the validate for simple is only able to validate one by one token?

`.simple("Response from Camel CDI on route ${rouxteId} using thread: ${threxdadName}");`

Validate only give me one error back in this case

**Comment by davsclaus** [comment]
Yeah it may fail at first error found

**Comment by davsclaus** [comment]
The first error causes the parser to may not be able to parse the rest etc. hence it fails fast afair
