### ISSUE TITLE
Real time endpoint validator in groovy off by one in annotate

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#144]
Notice how the red underline is off by one, and starts at &, = or ? character

![screen shot 2017-01-10 at 9 27 42 am](https://cloud.githubusercontent.com/assets/477100/21798898/2b190882-d717-11e6-8f57-c39e77b45ef8.png)

The same for Scala

![screen shot 2017-01-10 at 9 29 41 am](https://cloud.githubusercontent.com/assets/477100/21798935/57aa06b2-d717-11e6-954c-7c36fc0e2bb1.png)

That is not the case in Java or Kotlin where it works correct.

**Comment by fharms** [comment]
I better make some test case for Scala, Kotlin and Groovy

For some strange reason the TextRange behave different based on the different language types
```java
  startIdx = propertyValue.isEmpty() ? propertyIdx + 1 : fromElement.indexOf(propertyValue, startIdx) + 1;
  startIdx = IdeaUtils.isJavaLanguage(element) || IdeaUtils.isXmlLanguage(element) ? startIdx  : startIdx - 1;
  TextRange range = new TextRange(element.getTextRange().getStartOffset() + startIdx,
                    element.getTextRange().getStartOffset() + startIdx + propertyLength);
```

**Comment by davsclaus** [comment]
Yeah nothing should surprise us anymore with the IDEA Psi ;)

But at the end of the day its API is massive and we would still be in control, the cursor is blinking and we can write some code to fix/make it as we want

**Comment by fharms** [comment]
I solve this, but testing is another story since it requires Scala SDK available just to activate the annotator for scala files.

**Comment by fharms** [comment]
@davsclaus Do we have an example somewhere with Kotlin and Camel?

**Comment by davsclaus** [comment]
You can open the camel examples
https://github.com/apache/camel/tree/master/examples

there is a little scala, kotlin and groovy example there
