### ISSUE TITLE
Real time endpoint validator - Unknown option may highlight wrong

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#146]
In the rare case the endpoint path has a text that has the same name as an unknown option, then the validator may highlight that instead, eg

foo=bar is the unknown option problem, but you see

![screen shot 2017-01-10 at 10 48 31 am](https://cloud.githubusercontent.com/assets/477100/21801564/75be2eb6-d722-11e6-841a-505c9e077401.png)

**Comment by davsclaus** [comment]
So we should index for the unknown option after the `?` mark because its an unknown parameter.

**Comment by fharms** [comment]
@davsclaus It will not solve a case like this "timer:trigger?delay=1&fooo=bar&fooo" in this case. But I guess this is more a hypothetical problem than a real problem

**Comment by davsclaus** [comment]
Yeah that is more unlikely to happen
