### ISSUE TITLE
Camel facet

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#157]
Spring has a facet so when IDEA have detected its a spring project with spring xml file or spring boot etc, then it can setup a facet for that.

We could have a Camel facet, which has its own little Camel window, which can have a list of all the CamelContext / routes there is in the project, so you can navigate among them.

**Comment by adrianbumbas** [comment]
Things done so far:

- Enabled Camel facet

- The facet configuration page is empty

- Facet autodetection works only for XML files

What is difficult is to make it work for any other file types, apparently each file type needs another facet.

**Comment by adrianbumbas** [comment]
Apparently we need a facet for every file type 
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000031990-Facet-detector-for-multiple-file-types

**Comment by davsclaus** [comment]
I dont think a facet etc brings so much value. We can open tickets in the future if we find something cool to add
