### ISSUE TITLE
Smart completion - quick doc - Shows documentation for null in title

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#161]
Thanks @adrianbumbas this was great work.

I just noticed the title says documentation for null. I wonder if there is a way to make it show the name of the option?

See screenshot
![screen shot 2017-01-11 at 10 26 52 am](https://cloud.githubusercontent.com/assets/477100/21842800/9edad04e-d7e8-11e6-8ccf-194db3af181a.png)

**Comment by adrianbumbas** [comment]
I haven't noticed that. I will put the name of the option.

**Comment by davsclaus** [comment]
@adrianbumbas great, you can self assign tickets now, welcome to the team
