### ISSUE TITLE
Smart completion - Quick doc - More data to show

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#162]
We should show more information because we have more to show, for example something along the lines of:

<b>Name of option</b>
<b>Group:</b> the group (eg common, security, advanced, filter)
<b>Type:</b> the java type
<b>Default value:</b> the default value if any

Description

<b>Enums:</b>
enum1
enum2

**Comment by davsclaus** [comment]
Its the doc that is shown here I am talking about
https://github.com/davsclaus/camel-idea-plugin/blob/master/img/16-endpoint-smart-completion-quickdoc.png

**Comment by davsclaus** [comment]
@adrianbumbas I wonder if you want to take a look at this?

**Comment by adrianbumbas** [comment]
Sure, i will do it.

**Comment by davsclaus** [comment]
Thanks. I would suggest to remove the `Multi value` as its seldom used.
