### ISSUE TITLE
Do a special release with a lower since-build for users of older IDEA to try

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#168]
See
https://twitter.com/pcreddyn1/status/819199895340978176

**Comment by fharms** [comment]
We should be careful with that, since we are using API from 2016 SDK version and we might ending up releasing a version which say we support yearly version, but we really don't know

At least we should investigate if JetBrains is backward compatibility

**Comment by davsclaus** [comment]
Its a special release for feedback from different users what runs or what does not.

I dont really want to be limited to the latest and greatest version all the time.

**Comment by davsclaus** [comment]
In the start I was using 2016.2 version which worked fine at the time. 

I wonder if its possible to find older versions to download, it doesnt seem so easy to do

**Comment by davsclaus** [comment]
We have a twitter pool
https://twitter.com/davsclaus/status/819881627266465792

At that it seems most users are on 2016 so there is maybe not so many / demand for supporting older releases.

**Comment by fharms** [comment]
We could add instructions to the readme.md how they can change the plugin version and build for old versions

**Comment by davsclaus** [comment]
@fharms wonder if you wanted to add the readme instructions so we can get this ticket resolved

**Comment by fharms** [comment]
instruction added to readme.md on how to build for a older version of IDEA
