### ISSUE TITLE
Realtime Validation : getIndex match the position in the string, but not the position of the caret.

### ISSUE THREAD

**Issue by fharms** [davsclaus/camel-idea-plugin#169]
Since Camel Catelog have no knowledge about the caret position it report index based on it's location in the String. 

But it could be nice if it was possible to call thecatalogService.validateSimpleExpression with an option to marker the position in the error message so we can replace the position with the editor caret position.

> Unknown function: romuteId at location \<caret\>33\</caret\> Response from Camel CDI on route ${romuteId} using thread: ${threadName}

**Comment by fharms** [comment]
I guess until we get a more secure way to find the location number we can use the "location" in the error string to search for and replace

**Comment by davsclaus** [comment]
The index is the index within the simple string. I dont think it should be the offset from the current caret position in the editor that would be a bit odd imho.

However we could also remove that information and rely on the red underline highlighting, and then its just: `Unknown function: romuteId`.

**Comment by fharms** [comment]
I think is more odd you have to manually count the number of chars in the string rather just using the position from the ide. 

If we don't want to correct the location, then I think it's better we remove the location information as you suggested. 

<img width="804" alt="screen shot 2017-01-12 at 09 27 54" src="https://cloud.githubusercontent.com/assets/1123285/21882176/93698130-d8a9-11e6-9ff6-dcd9e08493e2.png">
<img width="228" alt="screen shot 2017-01-12 at 09 28 11" src="https://cloud.githubusercontent.com/assets/1123285/21882178/95770358-d8a9-11e6-854c-48ac08391bfd.png">

**Comment by davsclaus** [comment]
For example see last image at #172. That tooltip we could just say 'Unknown token *`.

**Comment by davsclaus** [comment]
Yes just having `Unknown function: crouteId` is imho better, then the tooltip is not so long either, and it does not repeat the simple string

**Comment by fharms** [comment]
So we need to parse the error text for either "Unknown token" or "Unknown function" and then strip the rest of the string?

**Comment by davsclaus** [comment]
Yeah I am adding to camel-catalog to provide a shortMessage as well so we can grab that and use.

**Comment by fharms** [comment]
Awesome let me know when it's ready 👍  I'm working on getting support for simple validation for the other languages

**Comment by davsclaus** [comment]
The next camel-catalog build from maven snapshot will have a `getShortError()` method on the result you can use.

**Comment by fharms** [comment]
@davsclaus Btw does this give us a problem with different version of the catalog? I remember something about you can use the same version as camel-core dependency

**Comment by davsclaus** [comment]
No we embed the latest camel-catalog and can use its latest API. The older downloaded camel-catalog is only used to read their embeded JSon files etc.

**Comment by davsclaus** [comment]
And the camel-catalog deals with older versions of camel-core so you dont have to worry about that, it did the same for the new getIndex method etc

**Comment by davsclaus** [comment]
With the new short error message then that logic to find the start index etc was reduced.

The current code starts from the index offset and for the remainder of the text. But we could consider stop at first whitespace ` ` or `}` assume its the end of that symbol/problem area.

**Comment by fharms** [comment]
Stange that should be caught by the test case

**Comment by fharms** [comment]
@davsclaus I'm on my way with a fix to this issue

**Comment by fharms** [comment]
I think I found  another error 

>  .loopDoWhile(simple("${body.length} =!!= 12"))

This is not validated as predicate because the code never go far enough back in the PSI tree to find parent method

**Comment by fharms** [comment]
I found where the issue is in isCameSimpleExpressionUsedAsPredicate and will create a test case for it

**Comment by fharms** [comment]
I managed to solve the problem "Cannot resolve symbol" for JDK classes by setting the below configuration. But there is still problem with "Cannot resolve symbol" for for Camel classes, though the camel-core is added to the test module as library as a dependency.

The result is the PSI parse doesn't see the Camel Java API as java syntax and treat it as plain text instead.

> -ea
-Xbootclasspath/p:../out/classes/production/boot
-XX:+HeapDumpOnOutOfMemoryError
-Xmx256m
-XX:MaxPermSize=320m
-Didea.home.path=/Users/workspace/work/idea/
-Didea.system.path=/Users/workspace/work/idea/test-system
-Didea.config.path=/Users/workspace/work/idea/test-config
-Didea.test.group=ALL_EXCLUDE_DEFINED

**Comment by fharms** [comment]
close solved in #177
