### ISSUE TITLE
The completion popup returns invalid string

### ISSUE THREAD

**Issue by adrianbumbas** [davsclaus/camel-idea-plugin#173]
When autocompleting a route with the schedulerProperties enpoint option the returned string is "scheduler."

This can also be seen in the quick documentation popup:

![image](https://cloud.githubusercontent.com/assets/1636509/21887070/b9a74ed0-d8be-11e6-97dd-7aa435f9bad0.png)

I've found the source of the issue on the CamelSmartCompletionEndpointOptions class line 72, not sure how to fix it. 
@davsclaus can you please take a look?

**Comment by davsclaus** [comment]
Yeah we needed to do some special logic if it was a multivalued prefix based option. Something a few options are, but you get now

![screen shot 2017-01-12 at 7 15 03 pm](https://cloud.githubusercontent.com/assets/477100/21902256/7fe3f12a-d8fb-11e6-9c25-d3d593558907.png)
