### ISSUE TITLE
Do a little animated git to show real time editor

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#175]
for the simple validator
and another for the smart completion of endpoints etc.

Such a animated gif can be nice to tweet for ppl to instant see the powers of this plugin.

However is there any good screencapture -> gif animate apps out there?

**Comment by davsclaus** [comment]
@fharms you have done some animated gifs on twitter. Wonder if you could find a couple and put in the source code so we can show them on github. Won't github show animated gifs? Would be nice to see on the front readme page.

**Comment by fharms** [comment]
sure, I'll add a few of them I have created or create some new if necessary
