### ISSUE TITLE
Quick doc in XML wont work if cursor is after an option

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#181]
eg this url

        <from uri="scheduler:foo?backoffErrorThreshold=4&amp;concurrentTasks=4"/>

The cursor is in the middle of the last option, eg concurrentTasks and then press ctrl + j

Then you dont get the component docs for the entire uri. But move the cursor to the first option and then you get it.

**Comment by adrianbumbas** [comment]
Somehow the documentation is being displayed for the xml attribute "uri" and is taken from the camel XSD file:

```
<xs:attribute name="uri" type="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en"><![CDATA[
Sets the uri of the endpoint to send to.
            ]]></xs:documentation>
          </xs:annotation>
        </xs:attribute>
```

@davsclaus it is possible to be an offset issue?

**Comment by davsclaus** [comment]
Ah its because `&amp;` breaks the psi element into pieces and you get a xml token and not xml attribute, and therefore dont have the entire string.

I think I got a fix for this
