### ISSUE TITLE
Simple annotator - Add support for scala, groovy and kotlin

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#187]
These need a bit more work to find out simple -> EIP which called them, and if its a predicate vs expression.

**Comment by davsclaus** [comment]
Groovy is now implemented.

**Comment by davsclaus** [comment]
A bit more complex scala code and it gets much more complex to find out this with all this AST parent / child / sibling check.

**Comment by rparree** [comment]
I'll have a look at this. Is the `org.apache.camel.idea.util.IdeaUtils#isPrevSiblingFromScalaMethod` method i am guessing that needs some work?

**Comment by davsclaus** [comment]
Yeah

**Comment by davsclaus** [comment]
Supporting those extra languages like Groovy and Scala is IMHO becoming a burden. 

So lets try to leave it as-is. Or find some way to make it optional and move to another maven module or something.
