### ISSUE TITLE
support jboss fuse camel version

### ISSUE THREAD

**Issue by luigidemasi** [davsclaus/camel-idea-plugin#191]
Using jboss fuse bom, camel version is not recognized
<img width="981" alt="schermata 2017-01-14 alle 21 17 41" src="https://cloud.githubusercontent.com/assets/5583341/21957527/cfc383da-daa0-11e6-96ea-80d77520a1c5.png">

**Comment by davsclaus** [comment]
@luigidemasi good idea. Do you have in the `pom.xml` file a setup for the JBoss Maven repository so the maven project can download the Fuse Camel JARs?

What we may need to do to support this is to detect that 3rd party Maven repo and use that to find the fuse version to be downloaded.

As a workaround you can try adding the fuse version of `camel-catalog` as a dependency in your pom.xml file. Then the plugin may find the JAR in your local m2 repo and dont need to download it over the internet

**Comment by luigidemasi** [comment]
@davsclaus yep, I have all fuse repos declared in the pom file, also tried to add the camel-catalog dependency without luck.

<img width="951" alt="schermata 2017-01-15 alle 13 15 17" src="https://cloud.githubusercontent.com/assets/5583341/21962096/79c05596-db25-11e6-95ed-313682a99080.png">

**Comment by davsclaus** [comment]
Okay got a prototype working for 3rd party repos

    12:53 PM	Camel IDEA plugin is using camel-catalog version 2.17.0.redhat-630187

**Comment by luigidemasi** [comment]
@davsclaus great!

**Comment by davsclaus** [comment]
Okay there is a new release with support for fuse. Let us know how it goes for you.

**Comment by luigidemasi** [comment]
Yep it works  👍 

<img width="957" alt="schermata 2017-01-15 alle 21 36 07" src="https://cloud.githubusercontent.com/assets/5583341/21965538/d3a7e1c4-db6a-11e6-902d-f643361d68be.png">
