### ISSUE TITLE
Simple annotator is broken

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#195]
Some recent code changes causes it to not match correctly

**Comment by fharms** [comment]
Could give an example so we can create a test case for it?

**Comment by davsclaus** [comment]
Wait a bit I have polished the unit test as some had a bit mistakes and a bit better simple testing.

**Comment by davsclaus** [comment]
It was mostly the || and some unit tests that was not totally corrected structured.

So Java and XML seems okay now. Will try to get that groovy added
