### ISSUE TITLE
Groovy simple validation - Highlight error with 1 char offset

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#202]
Just tried this to add log EIP to groovy and notice how the red underline is off by one char. It should be +1 later.

![screen shot 2017-01-15 at 5 56 59 pm](https://cloud.githubusercontent.com/assets/477100/21964430/33e18c30-db4c-11e6-91ce-15c95a910051.png)

**Comment by fharms** [comment]
Yeah, the text range start position is different based on the PSI element.
