### ISSUE TITLE
Intention is shown if the cursor is placed end of line

### ISSUE THREAD

**Issue by fharms** [davsclaus/camel-idea-plugin#204]
if you place the cursor end the of line the Intention is showed when press "ctrl + j"

> Exception exception = exchange.getException();\<caret\>

**Comment by davsclaus** [comment]
What intention is shown?

Its a good idea to paste screenshots as it help explain the problems

**Comment by fharms** [comment]
![image](https://cloud.githubusercontent.com/assets/1123285/22024855/afa9d5ea-dccb-11e6-9a68-9346fa577038.png)

**Comment by davsclaus** [comment]
Dont we want Camels everywhere ;)

**Comment by fharms** [comment]
No problem with me :-)
