### ISSUE TITLE
Smart completion: Type ahead is not working with smart completion

### ISSUE THREAD

**Issue by fharms** [davsclaus/camel-idea-plugin#207]
If you press ctrl-space for property placeholder and type ahead it's not finding the expected property name in the list

>simple("{{ + ctrl + space and type a property name

**Comment by davsclaus** [comment]
Remember to save the properties file first.

And what happens if there is no property. For my the type ahead seems working

![screen shot 2017-01-16 at 2 48 09 pm](https://cloud.githubusercontent.com/assets/477100/21985422/dce57018-dbfa-11e6-8f37-cc0d6261d282.png)

**Comment by fharms** [comment]
The property file was saved and I can scroll down to the property and select it.

There is multiple property files, so the list is very long

**Comment by fharms** [comment]
I restarted my IDEA and it's working again. 

No clue why it didn't work
