### ISSUE TITLE
Smart completion for values - Find list of existing beans

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#22]
Wonder if we can hook into spring / cdi / etc and get a list of beans, which the endpoints options that refer to beans, can use in the smart completion list.

eg if you have <bean> or spring boot beans or cdi beans or whatever.

**Comment by davsclaus** [comment]
And we should use `#beanName` style to refer to the bean by its name for the smart completion values, eg `...filter=#myFilter'

**Comment by adrianbumbas** [comment]
@davsclaus what would be the search scope of the beans? 

For XML I can easily search in the current XML file and all of the XML imports but for Java I have no idea.

Do we need to prevent importing something that will fail to be resolved at runtime or not? I'm thinking about OSGI containers that can complicate the things.

**Comment by davsclaus** [comment]
Yeah at first its fine for XML - lets focus on that as its easier as you say, its <bean> in both spring and blueprint xml files.

For Java lets create another ticket and discuss there.

**Comment by adrianbumbas** [comment]
This is how it looks:
<img width="632" alt="screen shot 2017-02-24 at 19 54 01" src="https://cloud.githubusercontent.com/assets/1636509/23316558/33a75260-facb-11e6-8454-116b72120350.png">

In the completion popup it shows all the beans that inherit the wanted class or interface located in the Intellij application context (if the Spring facet is configured). Thus the search scope can be at maximum the IntelliJ module.

@davsclaus is this ok?

**Comment by davsclaus** [comment]
@adrianbumbas yeah that looks great. Mind that when the value is inserted, it should use `#` syntax in Camel to refer to beans: eg

"cxf:bean:soapMessageEndpoint?bus=#blueprintBus"

Notice how the `#` is prefixed before the bean id.

There is a section about referring beans in the docs: http://camel.apache.org/how-do-i-configure-endpoints.html

**Comment by adrianbumbas** [comment]
@davsclaus ok,done that.

Now i'm struggling to fix the existing unit test. The Spring Intellij plugin depends on the java-i18n plugin. That plugin registers his own reference contribuitor which interferes with the `PropertyEndpointSmartCompletionTestIT` unit test. I'm currently having fun debugging the paltform.

**Comment by adrianbumbas** [comment]
Figured out the issue: 

The `com.intellij.lang.properties.PropertiesReferenceContributor` from the `com.intellij.java-i18n` plugin is registered in place of `CamelPropertiesOrYamlFileReferenceContributor`.

This can be solved in the `plugin.xml` file by adding `order="FIRST"` to the `CamelPropertiesOrYamlFileReferenceContributor`.

**Comment by adrianbumbas** [comment]
I now realize that the Spring plugin works only with the Ultimate version.

http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/spring_api.html

The Travis build is using the Community edition.

**Comment by fharms** [comment]
@adrianbumbas bommer, do you need any specific IDEA spring artifacts or can you depend on the spring artifacts from maven?

**Comment by adrianbumbas** [comment]
I need the Spring plugin to be enabled in IDEA, it would not even run on the Community edition. I develop everything on the Ultimate edition and I never thought that it will not work on the Community. Lesson learned.

**Comment by fharms** [comment]
Well I guess you need to make it a optional dependency. I'm not sure if it possible but you might be able to install as part of the testing. 

I describe an issue with other language support in #285 and testing we to look into.

**Comment by adrianbumbas** [comment]
If I understand this correctly the optional dependency allows some feature to be enabled in your plugin only if a certain plugin is present. This should do the trick, but the Spring IDEA jars must be in classpath so that the unit test passes, for that the Travis build must be changed to use the IDEA Ultimate edition.

Do I have any other alternative?

**Comment by fharms** [comment]
If you can't find it in the plugins browser I guess there is no way of intalling the Spring IDEA jars in the community edition

**Comment by davsclaus** [comment]
Yeah they have some plugins that are private and only in the ultimate (paid) version - sadly spring is one of them.

**Comment by adrianbumbas** [comment]
Unfortunately this feature cannot be implemented.
