### ISSUE TITLE
Quick documentation popup incorrect title for XML

### ISSUE THREAD

**Issue by adrianbumbas** [davsclaus/camel-idea-plugin#228]
The quick doc popup doesn't show the correct element in the title for which doc is displayed. This is happening in routes where & is present or when the caret is at the end of the route.

Examples:
Caret is at the end of route definition
![route_end](https://cloud.githubusercontent.com/assets/1636509/22164930/acff5e56-df59-11e6-96e4-c21ecf6560fb.png)
Caret is on the &amp;
![caret_amp](https://cloud.githubusercontent.com/assets/1636509/22164929/acfe0d76-df59-11e6-9848-f70a76ae7441.png)

**Comment by davsclaus** [comment]
Thanks for spotting and fixing this
