### ISSUE TITLE
Smart completion for property placeholders

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#24]
So if you edit a camel endpoint such as

   jms:foo?concurrentConsumers={{ CURSOR HERE

And then can press ctrl + space then we should try to find any keys from .properties files and show in the list.

**Comment by fharms** [comment]
I got the first working prototype working with property placeholders
<img width="971" alt="screen shot 2016-12-29 at 16 32 29" src="https://cloud.githubusercontent.com/assets/1123285/21547165/9afb13d4-cde4-11e6-8170-2d787eddd9cf.png">

**Comment by davsclaus** [comment]
I wonder if we should skip by default

- java.*
- *Logger.*

So we dont include those kind in the list, but kinda only want our own custom like that activemq url you have set

**Comment by davsclaus** [comment]
We may have the spring boot auto configuration files for Camel components etc which we may want to filter out as well. As there is a lot of them they use a convention we can use to skip

   camel.springboot.*

which should be considered reserved for camel-spring-boot

**Comment by davsclaus** [comment]
Can we move the property placeholder to its own class instead of inside the CamelContributor. I would like to keep the contributor at a higher level.

**Comment by davsclaus** [comment]
Ah noticed if you add a new key=value in a properties file and then go back to the java route and try smart completion for `{{` then the new entry is not show. I think its something to do with the vfs file system is only loading from disk, where as your last change was only in-memory.

Not sure what IDEA have to offer for that, so you can load a file resource _safely_. 

To see the new entry you can save the properties file first.

**Comment by davsclaus** [comment]
Also you should skip the `target` directory (in fact you should only read from the sources directories, which normally is `src`. 

I got it to find `pom.properties` which is generated by maven
```
#Generated by Apache Maven
#Thu Dec 29 21:15:10 CET 2016
version=2.19.0-SNAPSHOT
groupId=org.apache.camel
artifactId=camel-example-spring-boot
```

And I got these 3 options in my list

**Comment by fharms** [comment]
Regarding the new property file is not showing is because IDEA cache the completion list, but if you delete the "{{" and add them again the list is updated

**Comment by fharms** [comment]
The target directory we can filter out, but limit it to the src folder might be wrong. 

What if they for some reason has property files outside the src directory?

**Comment by davsclaus** [comment]
Have you tried to load the data with

    virtualFile.contentsToByteArray()

And then read the data from that byte[] it may contain all the latest data?

**Comment by davsclaus** [comment]
Yeah you can maybe somehow find that out in IDEA with some project meta-data because IDEA stores what are

- source folders
- resource folders
- output folders
- excluded folders
- and so on

eg look in project structure -> modules

**Comment by fharms** [comment]
I don't think the virtualFile.contentsToByteArray() change anything, because it's not the VFS system that is the issue. The VFS just gives us a list of property files files and with the path we are actually reading the physical file and update the ResultSet.

But IDEA don't see the changes before you delete the "{{".  We need to figure out how to tell IDEA it should invalidate it's cache

**Comment by fharms** [comment]
Alright I will see if I can make it more intelligent about where it search for property files

**Comment by davsclaus** [comment]
I have tried to find a way to make idea show the very latest content in the list, but it seems its reading stale content regardless if i use document manager and document instead of virtual file. Also the document manager says false to hasUnsavedChanges.

Okay lets leave it as is, and open new tickets if there is things to improve
