### ISSUE TITLE
Camel route start is incorrectly detected for Java 

### ISSUE THREAD

**Issue by adrianbumbas** [davsclaus/camel-idea-plugin#242]
The method `CamelIdeaUtils.isCamelRouteStart` returns true for all the `PsiElements` of a Java Camel route.

Example: for `from("file:inbox")` it returns true for the following elements:

<img width="512" alt="screen shot 2017-01-27 at 21 34 43" src="https://cloud.githubusercontent.com/assets/1636509/22386853/40d3dd12-e4d9-11e6-9acd-debf9bffa1f5.png">

It should return true only for "file:inbox" just like for XML.

**Comment by adrianbumbas** [comment]
Added unit test to prove that in PR #243

**Comment by adrianbumbas** [comment]
I was able to reduce the number of detected elements from 8 to 2 :)

To continue further is very tricky because `"file:inbox"` is at the same time a `PsiJavaToken` and `PsiLiteralExpression` but a `PsiJavaToken` is not a `PsiLiteralExpression`. The annotator needs a `PsiLiteralExpression` and the completion needs a `PsiJavaToken`.

Any suggestions?

**Comment by davsclaus** [comment]
Maybe you can add a parameter that includes which psi element you want to use or something. Also mind that in XML then the psi elements are different, and so are they in groovy, scala etc.

**Comment by adrianbumbas** [comment]
I'm trying to use that no success so far, the annotator test are failing anyway, not sure why.
Relying on string literals is not the best option since this route

` String uri = "direct:cafe";`
 `from(uri)...`

is not detected as being a Camel route.

**Comment by davsclaus** [comment]
Ah yeah the latter I dont think is yet supported as it requires a bit more logic to determine this and find out its a reference to a variable, and where that variable is, and find out if that is a string etc, or a `org.apache.camel.Endpoint` type etc.

**Comment by davsclaus** [comment]
We should fix so there is only one Camel icon shown, eg in the line where `<from>` or `from` is. See for example those 4 icons at this picture: https://cloud.githubusercontent.com/assets/1123285/22860595/f177158c-f102-11e6-8423-b5838be42e81.gif

**Comment by davsclaus** [comment]
This is fixed recently

**Comment by adrianbumbas** [comment]
@davsclaus why do you think that this is fixed, the unit test still shows that there are 8 routes:

https://github.com/davsclaus/camel-idea-plugin/blob/master/camel-idea-plugin/src/test/java/org/apache/camel/idea/util/IdeaUtilsIsCamelRouteStartTestIT.java#L88

**Comment by davsclaus** [comment]
It may be but what does it help the end user. Don't the plugin work okay so far.

I dont want to keep tickets open forever we dont work on. If you plan to work or revist this then you are welcome to reopen
