### ISSUE TITLE
Upgrade travis to use never version of IDEA

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#251]
I think there is a newer 2016.3.4 version out.

**Comment by davsclaus** [comment]
@fharms our travis CI server had trouble the last couple of times due that version of IDEA it downloads is corrupt or something. Maybe try to find a newer version

**Comment by fharms** [comment]
@davsclaus We get an access denied from https://download-cf.jetbrains.com/idea/ideaIC-2016.3.2.tar.gz

Not sure why
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DC4135E2A830465A</RequestId>
<HostId>
hcYEy7phUDotf9qZyoXHuzkZL8zYGO2z25aqaMeGHMzAMGtAO6soFylhbmFT/oB339px/VvRFbA=
</HostId>
</Error>```

**Comment by davsclaus** [comment]
Try with their new version 2016.3.3 in the url

**Comment by fharms** [comment]
that works. I'll create PR later to fix this
