### ISSUE TITLE
Plugin don't work when camel dependency added by gradle

### ISSUE THREAD

**Issue by RayKV** [davsclaus/camel-idea-plugin#257]
Plugin will initialize only if project have dependencies like:
- org.apache.camel : camel-core
- maven : org.apache.camel : camel-core

and won't initialize with gradle dependency 
- gradle : org.apache.camel : camel-core

**Comment by fharms** [comment]
Thanks for reporting this. 

I'm using camel plugin with a gradle project and it still see it as `maven : org.apache.camel : camel-core`, tough it's defined as a gradle dependencies.

I'm wonder what the different is, what version of IDEA are you using and could you sent a example of the gradle file?

**Comment by davsclaus** [comment]
Ah yeah maybe we should check if its `maven :` or `gradle :` as prefix to filter out that. I dont recall seeing `gradle`

**Comment by RayKV** [comment]
IntelliJ IDEA 2016.3.3
Build #IU-163.11103.6, built on January 16, 2017

Its gradle project generated by spring initializr

[build.gradle.zip](https://github.com/davsclaus/camel-idea-plugin/files/752274/build.gradle.zip)

![image](https://cloud.githubusercontent.com/assets/7491724/22618575/afe609e0-eae8-11e6-8d57-b9be53483d70.png)

**Comment by davsclaus** [comment]
@RayKV thanks. And you are using the latest Camel IDEA plugin right? 0.3.6

**Comment by davsclaus** [comment]
@fharms I wonder if you have time to look into this, and also of interrest for you as a gradle user

**Comment by fharms** [comment]
@davsclaus sure it will be sometime next week, since we have a release this weekend.

But I don't see the problem in my setup with gradle, so I need to replicate @RayKV setup to reproduce it

**Comment by RayKV** [comment]
@davsclaus Yes, I use version 0.3.6.

**Comment by rparree** [comment]
I have the same problem with sbt. I could open another issue, but believe it is caused by the same.

**Comment by rparree** [comment]
I believe you should also add

```java
split[0].equalsIgnoreCase("sbt")
```

I can check this if you want later this week.

**Comment by davsclaus** [comment]
Can you log a new ticket about SBT. Its not something we have supported before.

**Comment by davsclaus** [comment]
I pushed a sbt fix
https://github.com/davsclaus/camel-idea-plugin/commit/5c73e3795c065f81c161ef14e2260f8591a6de2f

We will do a release then you can test that release and report back
