### ISSUE TITLE
Route navigation - refine search scope

### ISSUE THREAD

**Issue by adrianbumbas** [davsclaus/camel-idea-plugin#264]
In order to find the Camel routes currently a search is made in the whole project including in files that cannot contain Camel routes like *.xsd, *.html, pom.xml etc

@davsclaus it makes sense to look also in the jar files? What if the routes are defined there?

**Comment by davsclaus** [comment]
IMHO it does not make sense to search in JAR files as users tend to have all their Camel routes in the same project. 

For files to search for routes then we have some code that can check if its from supported file extensions eg java, xml, scala etc. Just search the code a bit and you find that.

**Comment by adrianbumbas** [comment]
@davsclaus can we close this?
