### ISSUE TITLE
Route navigation - navigate to interceptors

### ISSUE THREAD

**Issue by adrianbumbas** [davsclaus/camel-idea-plugin#275]
Given the following route:

`<interceptSendToEndpoint uri="destination">...`

`<from uri="something">`
`<to uri="destination">`

the user can click on the Camel gutter icon at the `<to>` line in order to navigate to the `<interceptSendToEndpoint>` line.

@davsclaus is this a valid use case?

**Comment by davsclaus** [comment]
No

We should only have a Camel icon in the <from> line. And only navigate to other routes where they use to -> something.

**Comment by adrianbumbas** [comment]
Ok.
