### ISSUE TITLE
Intention - Open component documentation in property files 

### ISSUE THREAD

**Issue by fharms** [davsclaus/camel-idea-plugin#29]
An intention or hint or something which allows you when the cursor is positioned on a Camel endpoint, to open the component documentation from the Camel website.

Look at the CamelDocumentationProvider for help

**Comment by fharms** [comment]
For some reason "any" is not supported for documentationProvider

`<lang.documentationProvider language="any" implementationClass="org.apache.camel.idea.CamelDocumentationProvider"/>`

**Comment by davsclaus** [comment]
This one allows to hook into properties files


    <lang.documentationProvider language="Properties" implementationClass="org.apache.camel.idea.CamelDocumentationProvider"/>

However because there is already spring boot and a default as well, then we are down to number 3, and therefore are not in use as the others provides the docs first.

![screen shot 2016-12-29 at 11 18 21 am](https://cloud.githubusercontent.com/assets/477100/21541692/abc2cd32-cdb8-11e6-83de-a14cc94517f3.png)

**Comment by davsclaus** [comment]
I have not found a way to resort the list or somehow get priority so your own documentation provider have a chance to react before the others.

**Comment by fharms** [comment]
The only reason why language="Properties" is working in your case, is because you have the property plug-in on the classpath, right?

But I guess it make sense to be depended on the property plugin

**Comment by davsclaus** [comment]
Is it not installed OOTB? 

I got some code that likely works, found a way to hook into it

**Comment by fharms** [comment]
I had to specific add the property plugin to the classpath before it worked. But maybe I have not setup the project SDK correctly

**Comment by davsclaus** [comment]
I dont have it explicit on the classpath, but do a check on its class name to know if its from properties. I configure the plugin to have depends on properties so IDEA plugin manager should handle that.
