### ISSUE TITLE
Plugin misreporting error when applying value through a variable

### ISSUE THREAD

**Issue by CognitiveJ** [davsclaus/camel-idea-plugin#290]
Take the following example; 

`uriString.append(String.format("file://%s?startingDirectoryMustExist=true&fileExist=%s&autoCreate=false", directoryTransportDestination.location, directoryTransportDestination.fileExists));
`
The plugin reporting that this is incorrect when the code is correct - also, intellij allows you to supress errors but the plugin has no such feature which could solve the above. 

This is quite a serious bug as it then marks the entire package as having an error.
 
![image](https://cloud.githubusercontent.com/assets/19301595/23606509/f76e4bf6-0258-11e7-94ba-1288ae83dcce.png)

![image](https://cloud.githubusercontent.com/assets/19301595/23606603/560aba28-0259-11e7-825c-6bcbd60c3b50.png)

**Comment by fharms** [comment]
It's a known issue that we not able to runtime compile URI with variables and property placeholders for validation and completion

We properly need to find a way to suppress to start with.

**Comment by davsclaus** [comment]
You are a bit of the beaten track where you build some url yourself using String.format.

Camel has toF to fromF that is using string format style.

But yeah we can try to make IDEA plugin detect its String.format and do similar as it does for toF and fromF today
