### ISSUE TITLE
Documentation - The cmd hover over no longer work

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#30]
after the latest refactor. Not sure why as the documentation provider class is unchanged.

**Comment by fharms** [comment]
Strange, it might be a site effect from my refactor.

**Comment by davsclaus** [comment]
See #31 we can try to do it for F1 and then have some way to link / show full docs.

This issue could also be an IDEA bug or something.

**Comment by fharms** [comment]
Mayby. 

But it seems that it doesn't recognize the camel URI as keywords and never call the CompositeDocumentationProvider

**Comment by fharms** [comment]
Spend most of the day on this issue without finding a solution. I have parked it for now and working on another issue

**Comment by davsclaus** [comment]
Thanks, yeah could also be issue/bug in IDEA. 

I can try to take a look if I get some time later.

**Comment by davsclaus** [comment]
Okay we now make F1 show internal docs, and shift + f1 shows external which opens on github
