### ISSUE TITLE
One instance of CamelCatalog

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#34]
We need to use one instance of CamelCatalog so we use the same.

Also later when we add support for adding custom Camel components, switching to version of Camel catalog based on what Camel version the user has in his/her project, we need these changes on the same instance for the entire plugin code.

We can likely use a static instance as there is one plugin only.

Maybe have a CamelCatalogService where we have this static which we then use to get hold of.

**Comment by fharms** [comment]
FYI it's already static in Camel contributor. But I guess it make sense to move it out, if other classes need access

**Comment by davsclaus** [comment]
Yeah that makes it stand out more, you are welcome to work on this
