### ISSUE TITLE
Only active Camel plugin if its a Camel project

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#45]
We should add some logic in project open / close etc to detect if its a Camel project (eg has camel-core on dependency classpath) and if so only active the Camel smart completions if so.

**Comment by davsclaus** [comment]
There is some IDEA api for Component which has callbacks for projectOpen / projectClose etc.

I wonder if there is some api / listener in IDEA so we can listen when dependencies are added/removed/updated on the project. Then we can use that to detect if Camel is on the classpath or not, and thus if its a Camel project or not.

**Comment by fharms** [comment]
Yeah I found the ProjectComponent interface where you can add listener for project events and I got something up and running that scan the module libs.

The hard part is to figure out how to bypass the plugin or stop it for loading. My current solution will be to registre a flag in ServiceManager and test for this in the various contributors. Which remind me that I have refactored the CamelCatalogService to be registered in the ServiceManager instead of a static class to follow the SDK best practices

**Comment by davsclaus** [comment]
Oh its fine for the plugin to load, we just have some static api to call which returns true|false if its a camel project, and then stop doing what we do.

eg saying no to isValid etc in those completers and so on

**Comment by fharms** [comment]
@davsclaus do you think it's enough we just check if the file name contains "camel-core" or should we scan inside the JAR files? I'm concerned with the performance if need to scan every jar files contents.

Or do you have another suggestion?

**Comment by davsclaus** [comment]
See this code
https://github.com/davsclaus/camel-idea-plugin/blob/master/src/main/java/org/apache/camel/idea/intention/CamelAddEndpointIntention.java#L60

We can just find `org.apache.camel:camel-core` on the dependency classpath (eg also transitive) then we know its a Camel project.

Notice how the code checks with Maven, eg IDEA return it as a string with Maven as prefix. Not sure how gradle would do.

**Comment by fharms** [comment]
What if the user added the library on it own, the we can't be sure it's "org.apache.camel:camel-core"

If we test for "camel-core" we should be pretty sure

**Comment by davsclaus** [comment]
Yeah camel-core should be unique.

**Comment by fharms** [comment]
what if only "camel-core-xml" and "camel-core-osgi" is on the classpath, is that valid?

**Comment by davsclaus** [comment]
No camel-core must be on the classpath, you cannot run camel without it

**Comment by davsclaus** [comment]
Great work, is there more to this ticket, if so you can close it
