### ISSUE TITLE
Upload plugin release to Jetbrains repository from maven

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#61]
I wonder if there is a way to make maven build and upload the .zip file to jetbrains repository automatic.

Then we could have some release profile - goal etc and then travis CI could do it for us.

Currently we manually upload the .zip file at
https://plugins.jetbrains.com/idea/plugin/9371-apache-camel-idea-plugin?

**Comment by fharms** [comment]
I'm not sure how we can make travis-ci do it. This would require we can create specific job type we can trigger and I haven't seen that functionality.

**Comment by davsclaus** [comment]
Yeah I have not found anything either. However you can update a plugin from an url, so we could potentially release to maven central, and then point to that url in the jetbrains website where we can manually trigger the new version there.

However we would have to wait with using org.apache.camel as the group id as this code is not yet officially from ASF. 

But then again we can do that later when the code is donated to ASF.

**Comment by fharms** [comment]
another option could be to tag it in the commit log with a keyword and then we do some magic on travis ci if this is the case and publish it.

**Comment by davsclaus** [comment]
Ah yeah if travis can do a github release, and attach that target/camel-idea-plugin-VERSION.zip as a binary to a release, like we have done manually at
https://github.com/davsclaus/camel-idea-plugin/releases

Then there is a nice release at github, and we can then also use that url when we upload to jetbrains

**Comment by fharms** [comment]
See https://docs.travis-ci.com/user/deployment/releases/

**Comment by fharms** [comment]
@davsclaus we need to talk about this. I have been looking into how we can do this and it's not that simple as I thought because of the maven process and travis release feature

**Comment by davsclaus** [comment]
Yeah lets just update it manually. Its just a .zip file you upload so its simple enough for us to be able to do this
