### ISSUE TITLE
Warning/Error for incorrect endpoint paramaters or parameter values

### ISSUE THREAD

**Issue by mzubal** [davsclaus/camel-idea-plugin#64]
Hi there! The plugin rocks! It would be very nice feature to inform user about incorrect endpoint parameters or parameter values. The natural way of doing this could be using Warnings/Errors in IDEA.

**Comment by davsclaus** [comment]
Yeah its related to #10 but maybe we can also have a way of turning on / off showing validation errors in the source code editor by somehow flagging the error at the endpoint urls.

**Comment by fharms** [comment]
solved in PR #127
