### ISSUE TITLE
Speedup the install intellij libs script

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#67]
I wonder if we can speedup this script as its very slow
https://github.com/davsclaus/camel-idea-plugin/blob/master/install-intellij-libs.sh

It install all the JARs, maybe we can filter out that list and only install what we really only need.

**Comment by fharms** [comment]
I went through most of the JARs when setting up dependencies for plug-in testing. You can see them in the pom.xml file.

It not all, but it's close

**Comment by davsclaus** [comment]
Okay maybe we can wrap mvn install-file in our own maven plugin that can install this faster. I think its due to that script loop 100 JARs and then run a mvn install per file, which start a new JVM each time.

Instead if we can run only 1 JVM that embeds the install goal and run it in a for loop in java code, that can be much faster.

**Comment by fharms** [comment]
Another solution could be we are using Travis CI caching feature. Not entirely sure how we can test if it should run the installer or not but it might worth investigating 

See https://docs.travis-ci.com/user/caching/

**Comment by davsclaus** [comment]
Yeah I wonder if we can add the m2 repo as a cache
https://docs.travis-ci.com/user/caching/#Arbitrary-directories

And then in that install script we can check if the files are in the cache and avoid the maven install-file script that takes 10 minutes to run

**Comment by fharms** [comment]
closing this because we down to 2 min when Travis CI is building and for local development you only do this one time
