### ISSUE TITLE
Unit test error

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#68]
I get this error on my laptop
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=320m; support was removed in 8.0
Running org.apache.camel.idea.completion.extension.YamlPropertyPlaceholdersSmartCompletionTestIT
log4j:WARN No appenders could be found for logger (#com.intellij.util.ui.JBUI).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.998 sec <<< FAILURE! - in org.apache.camel.idea.completion.extension.YamlPropertyPlaceholdersSmartCompletionTestIT
testCompletion(org.apache.camel.idea.completion.extension.YamlPropertyPlaceholdersSmartCompletionTestIT)  Time elapsed: 2.674 sec  <<< ERROR!
java.lang.RuntimeException: Cannot load resource: /idea/IdeaApplicationInfo.xml
	at org.apache.camel.idea.completion.extension.YamlPropertyPlaceholdersSmartCompletionTestIT.setUp(YamlPropertyPlaceholdersSmartCompletionTestIT.java:31)
Caused by: java.io.FileNotFoundException: /idea/IdeaApplicationInfo.xml
	at org.apache.camel.idea.completion.extension.YamlPropertyPlaceholdersSmartCompletionTestIT.setUp(YamlPropertyPlaceholdersSmartCompletionTestIT.java:31)


Results :

Tests in error:
  YamlPropertyPlaceholdersSmartCompletionTestIT>UsefulTestCase.defaultRunBare:372->setUp:31->LightCodeInsightFixtureTestCase.setUp:113 » Runtime

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

I wonder if that `/idea/IdeaApplicationInfo.xml` path is some hardcoded value to refer to the root folder?

**Comment by davsclaus** [comment]
Also when the test runs it complain about log4j, maybe try to find out to add a src/test/resources/log4j.properties file the test can use

**Comment by fharms** [comment]
did you run the install-intellij-libs.sh again after your merged?

**Comment by davsclaus** [comment]
Yes it has installed those JARs

**Comment by davsclaus** [comment]
I ran

     ./install-intellij-libs.sh 2016.3.2 /Applications/IntelliJ\ IDEA.app/Contents/

**Comment by fharms** [comment]
I wonder if this has something to do with the version of IDEA you have installed. Because the /idea/IdeaApplicationInfo.xml is not a file I remember from any places

**Comment by davsclaus** [comment]
Its the latest ultimate version 2016.3.2

**Comment by fharms** [comment]
I'm using the community edition and the same version is downloaded on Travis CI.

Could you try that and re-run the install-intellij-libs?

**Comment by fharms** [comment]
I get the same error with the Ultimate version

**Comment by fharms** [comment]
I have something working on my machine now with Ultimate version.

It turned out I need to remove the " -Didea.platform.prefix=Idea" from args line and add 2 other dependencies

> <dependency>
      <groupId>com.intellij</groupId>
      <artifactId>jsp-api</artifactId>
      <version>${idea.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.intellij</groupId>
      <artifactId>idea-jsp-openapi</artifactId>
      <version>${idea.version}</version>
      <scope>test</scope>
    </dependency>

I haven't tested how it works with the community version, because the "-Didea.platform.prefix=Idea" was a requirement to run the test from maven

Go figure!

**Comment by fharms** [comment]
And then it starts :

>[WARNING] The POM for com.intellij:jsp-api:jar:2016.3.2 is missing, no dependency information available
[WARNING] The POM for com.intellij:idea-jsp-openapi:jar:2016.3.2 is missing, no dependency information available

This is not part of the community version 👎

**Comment by fharms** [comment]
We could setup a profile for those are using the Ultimate version and include the missing dependencies? So default behaviour is for the community version

What do you think @davsclaus ?

**Comment by davsclaus** [comment]
@fharms +1 for a profile.

Maybe down the road will should point the Jetbrain guys to here so they can see some of the good, bad, and ugly for plugin developers.
