### ISSUE TITLE
Add support for celyon

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#77]
Like we have done recently for kotlin, groovy etc.

We can build a little camel example which is good for testing / trying it out
https://issues.apache.org/jira/browse/CAMEL-10671

**Comment by akoufoudakis** [comment]
Hi!
Did you mean ceylon?

**Comment by davsclaus** [comment]
Yeah

**Comment by akoufoudakis** [comment]
Made it working with Jetty9 component, following the examples with groovy and kotlin... Will try with undertow.

**Comment by davsclaus** [comment]
Thanks for helping

**Comment by davsclaus** [comment]
Not having time to add yet another language, and Camel users are not using Celyon language
