### ISSUE TITLE
Preference page

### ISSUE THREAD

**Issue by fharms** [davsclaus/camel-idea-plugin#94]
We should allow the user to change some of the preferences for the plug-in through the IDEA preferences dialog

- Add or remove to the property placeholder ignore list
- Change Camel Catalog version
- Show Camel icon in gutter yes|no

This list will properly grow as we extend the plug-in with new features

**Comment by davsclaus** [comment]
The Camel catalog version ought to auto detect what you use, eg 2.18.1 etc. But maybe using the preference you can turn this on / off.

Also if the plugin needs to download a catalog for a different version it has to do this over the internet, which means http proxy issues for some people.

**Comment by davsclaus** [comment]
Also to

- show Camel icon in gutter yes|no

**Comment by davsclaus** [comment]
There is a little example here
https://github.com/forge/intellij-idea-plugin/blob/master/src/main/java/org/jboss/forge/plugin/idea/ui/ForgePreferencePage.java

**Comment by davsclaus** [comment]
So we have an initial preference, then we can add options for these other things.

Its a bit harder to add/remove package names for property key filters as that requires a more advanced UI with some add/remove lines. But we can look at the other plugins and their preferences to be inspired.

**Comment by davsclaus** [comment]
@fharms this PR shows how to add a new option to the preference
https://github.com/davsclaus/camel-idea-plugin/pull/132
